/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API for Password, Passkey, Magic Link, and OIDC Authentication
 * API for user registration and authentication using multiple methods: username/password with capability of 2fa, passkey (WebAuthn), magic link, and OIDC providers (Google, GitHub, etc.).

 * OpenAPI spec version: 1.0.0
 */
import type {
  LoginSuccessResponse,
  MFARequestChangePasswordSuccessReponse,
  MFARevokeSuccessReponse,
  MFAVerifySetupSuccessResponse,
  MfaBackupCodeConsumeMutationFnBody,
  MfaBackupCodeLoginMutationFnBody,
  MfaRevokeMutationFnBody,
  MfaSetupResponse,
  MfaVerifyForgotPasswordMutationFnBody,
  MfaVerifyLoginMutationFnBody,
  MfaVerifyMutationFnBody
} from './client.schemas';

import { customAxiosInstance } from '../../config/axios.config';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Initiates the setup process for Multi-Factor Authentication (MFA) using TOTP (Time-Based One-Time Password). 
Returns a temporary secret key and a QR code that the user can scan in their authenticator app (e.g., Google Authenticator, Authy). 
The temporary secret must be verified by the user to finalize MFA enrollment. 
This endpoint requires the user to be authenticated via a valid access token cookie.

 * @summary Retrieve temporary TOTP secret and QR code for MFA setup
 */
export const mfaSetupQueryFn = (
    
 options?: SecondParameter<typeof customAxiosInstance<MfaSetupResponse>>,) => {
      return customAxiosInstance<MfaSetupResponse>(
      {url: `/mfa/setup`, method: 'GET'
    },
      options);
    }
  /**
 * Verifies the multi-factor authentication (MFA) code provided by the user. This step is required after MFA setup or during a login flow to validate the one-time code generated by the authenticator app or sent via email/SMS. Upon successful verification, the MFA setup is confirmed or the login session is allowed.

 * @summary Verify the MFA code for a user
 */
export const mfaVerifyMutationFn = (
    mfaVerifyMutationFnBody: MfaVerifyMutationFnBody,
 options?: SecondParameter<typeof customAxiosInstance<MFAVerifySetupSuccessResponse>>,) => {
      return customAxiosInstance<MFAVerifySetupSuccessResponse>(
      {url: `/mfa/verify`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: mfaVerifyMutationFnBody
    },
      options);
    }
  /**
 * Revokes (disables) Two-Factor Authentication (2FA) for the authenticated user.   The user must provide a valid MFA verification code generated by their authenticator app.   Once verified, the user's 2FA secret and backup codes will be permanently removed.

 * @summary Disable (revoke) Two-Factor Authentication (2FA) for the current user
 */
export const mfaRevokeMutationFn = (
    mfaRevokeMutationFnBody: MfaRevokeMutationFnBody,
 options?: SecondParameter<typeof customAxiosInstance<MFARevokeSuccessReponse>>,) => {
      return customAxiosInstance<MFARevokeSuccessReponse>(
      {url: `/mfa/revoke`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: mfaRevokeMutationFnBody
    },
      options);
    }
  /**
 * Disables Multi-Factor Authentication (2FA) for the currently authenticated user using one of their previously generated backup codes.   This endpoint can be used when the user no longer has access to their authenticator app but still possesses a valid backup code.   Upon successful verification of the provided backup code, all remaining backup codes are invalidated, the MFA secret is removed, and 2FA is fully disabled for the account.

 * @summary Disable Two-Factor Authentication (2FA) using a backup code
 */
export const mfaBackupCodeConsumeMutationFn = (
    mfaBackupCodeConsumeMutationFnBody: MfaBackupCodeConsumeMutationFnBody,
 options?: SecondParameter<typeof customAxiosInstance<MFARevokeSuccessReponse>>,) => {
      return customAxiosInstance<MFARevokeSuccessReponse>(
      {url: `/mfa/backup-code/consume`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: mfaBackupCodeConsumeMutationFnBody
    },
      options);
    }
  /**
 * Authenticates a user by consuming one of their valid MFA backup codes. This endpoint is typically used when a user cannot access their authenticator app but has saved backup codes.   Upon successful verification, a new authenticated session is created, access and refresh tokens are issued, and the used backup code is invalidated (removed from the account).   The `mfaToken` cookie used during the MFA flow is cleared upon successful login.

 * @summary Log in using a backup code
 */
export const mfaBackupCodeLoginMutationFn = (
    mfaBackupCodeLoginMutationFnBody: MfaBackupCodeLoginMutationFnBody,
 options?: SecondParameter<typeof customAxiosInstance<LoginSuccessResponse>>,) => {
      return customAxiosInstance<LoginSuccessResponse>(
      {url: `/mfa/backup-code/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: mfaBackupCodeLoginMutationFnBody
    },
      options);
    }
  /**
 * Validates the one-time MFA code provided by the user during the login process.   This endpoint finalizes the multi-factor authentication (MFA) login flow by verifying the 6-digit time-based one-time password (TOTP) generated by the user’s authenticator app.   Upon successful verification, a new authenticated session is created, and both access and refresh tokens are issued. The temporary `mfaToken` cookie is cleared once login is complete.

 * @summary Verify MFA code during login
 */
export const mfaVerifyLoginMutationFn = (
    mfaVerifyLoginMutationFnBody: MfaVerifyLoginMutationFnBody,
 options?: SecondParameter<typeof customAxiosInstance<LoginSuccessResponse>>,) => {
      return customAxiosInstance<LoginSuccessResponse>(
      {url: `/mfa/verify/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: mfaVerifyLoginMutationFnBody
    },
      options);
    }
  /**
 * Verifies the one-time MFA code submitted by the user in order to proceed with a password reset.   Upon successful verification, a password reset email is sent to the user's registered email address with a link to complete the password change process.   This endpoint also clears the temporary MFA token cookie to prevent reuse.

 * @summary Verify MFA code for password reset
 */
export const mfaVerifyForgotPasswordMutationFn = (
    mfaVerifyForgotPasswordMutationFnBody: MfaVerifyForgotPasswordMutationFnBody,
 options?: SecondParameter<typeof customAxiosInstance<MFARequestChangePasswordSuccessReponse>>,) => {
      return customAxiosInstance<MFARequestChangePasswordSuccessReponse>(
      {url: `/mfa/verify/forgot-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: mfaVerifyForgotPasswordMutationFnBody
    },
      options);
    }
  export type MfaSetupQueryFnResult = NonNullable<Awaited<ReturnType<typeof mfaSetupQueryFn>>>
export type MfaVerifyMutationFnResult = NonNullable<Awaited<ReturnType<typeof mfaVerifyMutationFn>>>
export type MfaRevokeMutationFnResult = NonNullable<Awaited<ReturnType<typeof mfaRevokeMutationFn>>>
export type MfaBackupCodeConsumeMutationFnResult = NonNullable<Awaited<ReturnType<typeof mfaBackupCodeConsumeMutationFn>>>
export type MfaBackupCodeLoginMutationFnResult = NonNullable<Awaited<ReturnType<typeof mfaBackupCodeLoginMutationFn>>>
export type MfaVerifyLoginMutationFnResult = NonNullable<Awaited<ReturnType<typeof mfaVerifyLoginMutationFn>>>
export type MfaVerifyForgotPasswordMutationFnResult = NonNullable<Awaited<ReturnType<typeof mfaVerifyForgotPasswordMutationFn>>>
