/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API for Password, Passkey, Magic Link, and OIDC Authentication
 * API for user registration and authentication using multiple methods: username/password with capability of 2fa, passkey (WebAuthn), magic link, and OIDC providers (Google, GitHub, etc.).

 * OpenAPI spec version: 1.0.0
 */
import type {
  DeleteSessionByIdSuccessResponse,
  GetAllSessionsSuccessResponse,
  GetCurrentSessionSuccessResponse
} from './client.schemas';

import { customAxiosInstance } from '../../config/axios.config';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Retrieves a list of all **active login sessions** associated with the authenticated user.   This endpoint allows a user to view all currently valid sessions across devices and browsers, helping with account activity monitoring and session management.  
Each returned session includes device information (`userAgent`), creation and expiration timestamps, and a boolean flag (`isCurrent`) indicating whether it corresponds to the current active session (the one used to make the request).  
Expired sessions are automatically filtered out and are **not included** in the response.

 * @summary Retrieve all active sessions for the authenticated user
 */
export const sessionAllGetQueryFn = (
    
 options?: SecondParameter<typeof customAxiosInstance<GetAllSessionsSuccessResponse>>,) => {
      return customAxiosInstance<GetAllSessionsSuccessResponse>(
      {url: `/session/all`, method: 'GET'
    },
      options);
    }
  /**
 * Retrieves the **current active session** for the authenticated user, based on the session ID stored in the request context.   This endpoint is primarily used to identify the session associated with the current request and to retrieve minimal user information .

 * @summary Retrieve the current user session
 */
export const sessionGetCurrentQueryFn = (
    
 options?: SecondParameter<typeof customAxiosInstance<GetCurrentSessionSuccessResponse>>,) => {
      return customAxiosInstance<GetCurrentSessionSuccessResponse>(
      {url: `/session/`, method: 'GET'
    },
      options);
    }
  /**
 * Deletes a specific user session identified by its ID.  The operation validates that the session exists and that the authenticated user has permission to delete it.  If the deleted session is the current session of the user, authentication cookies will be cleared, effectively logging the user out.
Responses include a success message and, if the current session was deleted, a `nextStep` indicating that the user should be redirected to the login page.
Possible errors:
  - 403 Forbidden: If the user tries to delete a session that does not belong to them.
  - 404 Not Found: If the session ID does not exist.

 * @summary Delete a user session by ID
 */
export const sessionRemoveByIdMutationFn = (
    id: string,
 options?: SecondParameter<typeof customAxiosInstance<DeleteSessionByIdSuccessResponse>>,) => {
      return customAxiosInstance<DeleteSessionByIdSuccessResponse>(
      {url: `/session/${id}`, method: 'DELETE'
    },
      options);
    }
  export type SessionAllGetQueryFnResult = NonNullable<Awaited<ReturnType<typeof sessionAllGetQueryFn>>>
export type SessionGetCurrentQueryFnResult = NonNullable<Awaited<ReturnType<typeof sessionGetCurrentQueryFn>>>
export type SessionRemoveByIdMutationFnResult = NonNullable<Awaited<ReturnType<typeof sessionRemoveByIdMutationFn>>>
