/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API for Password, Passkey, Magic Link, and OIDC Authentication
 * API for user registration and authentication using multiple methods: username/password with capability of 2fa, passkey (WebAuthn), magic link, and OIDC providers (Google, GitHub, etc.).

 * OpenAPI spec version: 1.0.0
 */
import type {
  AuthEmailVerifyMutationFnBody,
  AuthPasswordForgotMutationFn200,
  AuthSignInMutationFn200,
  EmailConfirmedSuccessResponse,
  ForgotPasswordRequestBody,
  LogoutSuccessResponse,
  RefreshTokenEndpointSuccessResponse,
  RegistrationSuccessReponse,
  ResetPasswordRequestBody,
  ResetPasswordSuccessResponse,
  UserLoginRequestBody,
  UserRegistrationRequestBody
} from './client.schemas';

import { customAxiosInstance } from '../../config/axios.config';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * This endpoint allows a new user to create an account using their email and password. After registration, the user must verify their email to complete the registration process successfully.
 * @summary Register a new user
 */
export const authSignUpMutationFn = (
    userRegistrationRequestBody: UserRegistrationRequestBody,
 options?: SecondParameter<typeof customAxiosInstance<RegistrationSuccessReponse>>,) => {
      return customAxiosInstance<RegistrationSuccessReponse>(
      {url: `/auth/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userRegistrationRequestBody
    },
      options);
    }
  /**
 * This endpoint allows an existing user to log in using their email and password. Upon successful authentication, an access token (and optionally a refresh token) is returned. If the user has two-factor authentication enabled, additional steps may be required to complete the login process.

 * @summary Authenticate a user with email and password
 */
export const authSignInMutationFn = (
    userLoginRequestBody: UserLoginRequestBody,
 options?: SecondParameter<typeof customAxiosInstance<AuthSignInMutationFn200>>,) => {
      return customAxiosInstance<AuthSignInMutationFn200>(
      {url: `/auth/signin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userLoginRequestBody
    },
      options);
    }
  /**
 * Verifies a user's email address using a verification token sent via email. Upon successful verification, the user's account is marked as confirmed, allowing them to complete the login process or other protected actions.

 * @summary Authenticate a user with email and password
 */
export const authEmailVerifyMutationFn = (
    authEmailVerifyMutationFnBody: AuthEmailVerifyMutationFnBody,
 options?: SecondParameter<typeof customAxiosInstance<EmailConfirmedSuccessResponse>>,) => {
      return customAxiosInstance<EmailConfirmedSuccessResponse>(
      {url: `/auth/email/verify`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authEmailVerifyMutationFnBody
    },
      options);
    }
  /**
 * Initiates the password reset process for a user by submitting their email address.  If the user has two-factor authentication (MFA) enabled, an MFA verification step will be required before sending the password reset instructions. Otherwise, a password reset email will be sent directly.

 * @summary Request a password reset for a user account
 */
export const authPasswordForgotMutationFn = (
    forgotPasswordRequestBody: ForgotPasswordRequestBody,
 options?: SecondParameter<typeof customAxiosInstance<AuthPasswordForgotMutationFn200>>,) => {
      return customAxiosInstance<AuthPasswordForgotMutationFn200>(
      {url: `/auth/password/forgot`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: forgotPasswordRequestBody
    },
      options);
    }
  /**
 * Completes the password reset process for a user account using a valid verification code.   The request must include the verification code (typically received via email) and the new password.   Upon successful verification, the user's password is updated, existing authentication cookies are cleared,   and the user is advised to log in again. If the password reset was not initiated by the user, they are encouraged   to contact support immediately. The operation also records contextual information such as IP address and user agent   for security auditing purposes.

 * @summary Complete the password reset process
 */
export const authPasswordResetMutationFn = (
    resetPasswordRequestBody: ResetPasswordRequestBody,
 options?: SecondParameter<typeof customAxiosInstance<ResetPasswordSuccessResponse>>,) => {
      return customAxiosInstance<ResetPasswordSuccessResponse>(
      {url: `/auth/password/reset`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: resetPasswordRequestBody
    },
      options);
    }
  /**
 * Issues a new access token (and optionally a new refresh token) for an authenticated session.   The request must include a valid **refresh token** stored in the user's HTTP-only cookie. If the refresh token is valid and the session is still active, a new access token will be returned and authentication cookies will be updated.   If the refresh token is expired, invalid, or mismatched, the session will be invalidated and all authentication cookies will be cleared to enforce re-authentication.   This endpoint ensures seamless session continuity while maintaining security best practices.

 * @summary Refresh the user's access token using a valid refresh token
 */
export const authRefreshTokenQueryFn = (
    
 options?: SecondParameter<typeof customAxiosInstance<RefreshTokenEndpointSuccessResponse>>,) => {
      return customAxiosInstance<RefreshTokenEndpointSuccessResponse>(
      {url: `/auth/refresh`, method: 'GET'
    },
      options);
    }
  /**
 * Terminates the current authenticated session by invalidating all active authentication tokens and clearing related cookies (`accessToken`, `refreshToken`).   This ensures that both the access token and any linked refresh token can no longer be used.   The endpoint is typically called when a user explicitly logs out or when a session needs to be forcefully closed for security reasons.   Requires a valid access token cookie for authentication and session validation.   After a successful logout, the client should remove any cached session state and redirect the user to a login page.

 * @summary Log out the authenticated user and invalidate the current session
 */
export const authLogoutMutationFn = (
    
 options?: SecondParameter<typeof customAxiosInstance<LogoutSuccessResponse>>,) => {
      return customAxiosInstance<LogoutSuccessResponse>(
      {url: `/auth/logout`, method: 'POST'
    },
      options);
    }
  export type AuthSignUpMutationFnResult = NonNullable<Awaited<ReturnType<typeof authSignUpMutationFn>>>
export type AuthSignInMutationFnResult = NonNullable<Awaited<ReturnType<typeof authSignInMutationFn>>>
export type AuthEmailVerifyMutationFnResult = NonNullable<Awaited<ReturnType<typeof authEmailVerifyMutationFn>>>
export type AuthPasswordForgotMutationFnResult = NonNullable<Awaited<ReturnType<typeof authPasswordForgotMutationFn>>>
export type AuthPasswordResetMutationFnResult = NonNullable<Awaited<ReturnType<typeof authPasswordResetMutationFn>>>
export type AuthRefreshTokenQueryFnResult = NonNullable<Awaited<ReturnType<typeof authRefreshTokenQueryFn>>>
export type AuthLogoutMutationFnResult = NonNullable<Awaited<ReturnType<typeof authLogoutMutationFn>>>
