/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API for Password, Passkey, Magic Link, and OIDC Authentication
 * API for user registration and authentication using multiple methods: username/password with capability of 2fa, passkey (WebAuthn), magic link, and OIDC providers (Google, GitHub, etc.).

 * OpenAPI spec version: 1.0.0
 */
import type {
  LoginSuccessResponse,
  MagicLinkSignInRequestBody,
  MagicLinkSignInSuccessResponse,
  MagicLinkSignUpRequestBody,
  MagicLinkSignUpSuccessResponse
} from './client.schemas';

import { customAxiosInstance } from '../../config/axios.config';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Registers a new user account by sending a **magic link** to the provided email address. 
The user can complete the signup process by clicking the link in the verification email. 
If the email is already associated with an existing account, the request will be rejected.  
This flow is typically used when passwordless authentication is enabled for the application.

 * @summary Register a new user using a magic link
 */
export const magicLinkSignUpMutationFn = (
    magicLinkSignUpRequestBody: MagicLinkSignUpRequestBody,
 options?: SecondParameter<typeof customAxiosInstance<MagicLinkSignUpSuccessResponse>>,) => {
      return customAxiosInstance<MagicLinkSignUpSuccessResponse>(
      {url: `/magic-link/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: magicLinkSignUpRequestBody
    },
      options);
    }
  /**
 * Initiates a passwordless sign-in flow by sending a magic link to the user email address. 
The user can authenticate by clicking the link received in their inbox. 
If the email is not associated with any account, the request will fail with a 404 response. 
This endpoint is typically used in passwordless authentication systems.

 * @summary Sign in a user using a magic link
 */
export const magicLinkSignInMutationFn = (
    magicLinkSignInRequestBody: MagicLinkSignInRequestBody,
 options?: SecondParameter<typeof customAxiosInstance<MagicLinkSignInSuccessResponse>>,) => {
      return customAxiosInstance<MagicLinkSignInSuccessResponse>(
      {url: `/magic-link/signin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: magicLinkSignInRequestBody
    },
      options);
    }
  /**
 * Resends a new generated magic link to the user's email address. 
This endpoint can be used when the user did not receive or accidentally deleted 
the original magic link for verification or sign-in. 
If the email does not correspond to an existing user, the request will fail with a 404 response. 
This operation is commonly used in passwordless authentication systems to handle failed or lost verification emails.

 * @summary Resend a magic link for email verification or sign-in
 */
export const magicLinkResendMutationFn = (
    magicLinkSignInRequestBody: MagicLinkSignInRequestBody,
 options?: SecondParameter<typeof customAxiosInstance<MagicLinkSignInSuccessResponse>>,) => {
      return customAxiosInstance<MagicLinkSignInSuccessResponse>(
      {url: `/magic-link/resend`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: magicLinkSignInRequestBody
    },
      options);
    }
  /**
 * Verifies a user's email or signs them in by validating the provided magic link token. 
This endpoint is typically triggered when the user clicks on the magic link sent to their email. 
Upon successful verification, authentication cookies or tokens are issued to establish the session.

 * @summary Verify a user's email using a magic link token
 */
export const magicLinkAuthenticateQueryFn = (
    token: string,
 options?: SecondParameter<typeof customAxiosInstance<LoginSuccessResponse>>,) => {
      return customAxiosInstance<LoginSuccessResponse>(
      {url: `/magic-link/authenticate/${token}`, method: 'GET'
    },
      options);
    }
  export type MagicLinkSignUpMutationFnResult = NonNullable<Awaited<ReturnType<typeof magicLinkSignUpMutationFn>>>
export type MagicLinkSignInMutationFnResult = NonNullable<Awaited<ReturnType<typeof magicLinkSignInMutationFn>>>
export type MagicLinkResendMutationFnResult = NonNullable<Awaited<ReturnType<typeof magicLinkResendMutationFn>>>
export type MagicLinkAuthenticateQueryFnResult = NonNullable<Awaited<ReturnType<typeof magicLinkAuthenticateQueryFn>>>
