/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API for Password, Passkey, Magic Link, and OIDC Authentication
 * API for user registration and authentication using multiple methods: username/password with capability of 2fa, passkey (WebAuthn), magic link, and OIDC providers (Google, GitHub, etc.).

 * OpenAPI spec version: 1.0.0
 */
import type {
  PasskeyAddedSuccessResponse,
  PasskeyCompletAuthenticationRequestBody,
  PasskeyCompletRegistrationRequestBody,
  PasskeyGenerateRemoveKeySuccessResponse,
  PasskeyGenerateSignInSessionSuccessResponse,
  PasskeyGenerateSignUpSessionSuccessResponse,
  PasskeyGetAllPasskeyByUserIdSuccessResponse,
  PasskeyRemovedSuccessResponse,
  PasskeySignInVerifyMutationFn200,
  PasskeySignUpInitMutationFnBody,
  RegistrationSuccessReponse
} from './client.schemas';

import { customAxiosInstance } from '../../config/axios.config';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Starts the registration process for a new user using passwordless passkey authentication.  The client provides the user's name and email address. If the email is not already registered, the server generates a **PublicKeyCredentialCreationOptions** object required by the WebAuthn API. This object includes a challenge, relying party information, user details, allowed algorithms, and authenticator selection criteria. It must be sent back to the client to complete the registration on the authenticator (device or platform). The server also stores a temporary PasskeyChallengeSession to track the challenge for later verification.

 * @summary Initialize a passkey registration session
 */
export const passkeySignUpInitMutationFn = (
    passkeySignUpInitMutationFnBody: PasskeySignUpInitMutationFnBody,
 options?: SecondParameter<typeof customAxiosInstance<PasskeyGenerateSignUpSessionSuccessResponse>>,) => {
      return customAxiosInstance<PasskeyGenerateSignUpSessionSuccessResponse>(
      {url: `/passkey/signup/init`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passkeySignUpInitMutationFnBody
    },
      options);
    }
  /**
 * Verifies a passkey registration session provided by the client to complete the user signup process.
The client must provide a `PasskeyRegistrationResponse` object containing the credential information generated during the passkey registration initiation.

 * @summary Verify a passkey registration session and complete user signup
 */
export const passkeySignUpVerifyMutationFn = (
    passkeyCompletRegistrationRequestBody: PasskeyCompletRegistrationRequestBody,
 options?: SecondParameter<typeof customAxiosInstance<RegistrationSuccessReponse>>,) => {
      return customAxiosInstance<RegistrationSuccessReponse>(
      {url: `/passkey/signup/verify`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passkeyCompletRegistrationRequestBody
    },
      options);
    }
  /**
 * Initializes a new **WebAuthn passkey authentication session** for a user who wants to sign in using a registered passkey.   The endpoint generates a new WebAuthn **authentication challenge** and returns a set of `PublicKeyCredentialRequestOptions` that the frontend must pass to the browser's WebAuthn API (`navigator.credentials.get`).  
The generated challenge is stored securely in the backend and will later be verified during the `/passkey/authenticate/verify` step.   No user identifier is required at this stage, as the passkey authenticator handles user identification during the authentication process.
This endpoint should be called from the frontend **before** invoking the browser WebAuthn API.
--- **Typical flow:** 1. Frontend calls `POST /passkey/authenticate/init` 2. Backend generates and stores challenge + session 3. Frontend receives `publicKeyCredentialRequestOptions` 4. Frontend calls `navigator.credentials.get(options)` with those options 5. The result is sent to `/passkey/authenticate/verify` for final verification

 * @summary Initialize a passkey authentication (sign-in) session
 */
export const passkeySignInInitMutationFn = (
    
 options?: SecondParameter<typeof customAxiosInstance<PasskeyGenerateSignInSessionSuccessResponse>>,) => {
      return customAxiosInstance<PasskeyGenerateSignInSessionSuccessResponse>(
      {url: `/passkey/signin/init`, method: 'POST'
    },
      options);
    }
  /**
 * Completes the **passkey-based sign-in process** by verifying the WebAuthn authentication response 
returned by the browser after calling `navigator.credentials.get()`.  

This endpoint:
  - Validates the cryptographic response (challenge, signature, authenticator data)
  - Ensures the passkey session is still valid and not consumed
  - Confirms that the user exists and is eligible for login
  - Creates a new authenticated session and issues secure access and refresh tokens

On success, the user is authenticated, tokens are issued, and authentication cookies are set.  
If the user's email has not yet been verified, the endpoint returns a pending verification response instead of logging in.

 * @summary Verify a passkey authentication response and complete user login
 */
export const passkeySignInVerifyMutationFn = (
    passkeyCompletAuthenticationRequestBody: PasskeyCompletAuthenticationRequestBody,
 options?: SecondParameter<typeof customAxiosInstance<PasskeySignInVerifyMutationFn200>>,) => {
      return customAxiosInstance<PasskeySignInVerifyMutationFn200>(
      {url: `/passkey/signin/verify`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passkeyCompletAuthenticationRequestBody
    },
      options);
    }
  /**
 * Initializes a **WebAuthn passkey registration session** that allows a logged-in user to securely add a new passkey to their account.  

This endpoint performs the following steps:
  1. Validates the authenticated user and checks that they match the `{userid}` path parameter.
  2. Retrieves existing passkeys associated with the account to prevent re-registration of the same authenticator.
  3. Generates a new **WebAuthn PublicKeyCredentialCreationOptions** object (challenge, relying party info, user identity, supported algorithms, etc.).
  4. Persists the challenge session in the database with the `"add-new-key"` purpose for later verification.

The client (frontend) should use the returned `publicKeyOpts` object as input for the `navigator.credentials.create()` call in the browser.

This route requires a valid **access token cookie** for authentication.

 * @summary Initialize a new passkey registration session for an authenticated user
 */
export const passkeyAddPasskeyByUserIdInitMutationFn = (
    userid: string,
 options?: SecondParameter<typeof customAxiosInstance<PasskeyGenerateSignUpSessionSuccessResponse>>,) => {
      return customAxiosInstance<PasskeyGenerateSignUpSessionSuccessResponse>(
      {url: `/passkey/add-passkey/init/${userid}`, method: 'POST'
    },
      options);
    }
  /**
 * Completes the registration of a new **Passkey** for the currently authenticated user.  
This endpoint verifies the passkey attestation response generated by the client after initiating the "Add new passkey" process.  

Once verification succeeds:
  - The passkey is securely registered and linked to the user’s account.
  - The corresponding challenge session is marked as consumed.
  - A success response containing the stored passkey details is returned.

Access to this endpoint requires a valid authenticated session and a matching user ID in the path parameter.

 * @summary Verify and finalize new Passkey registration
 */
export const passkeyAddPasskeyByUserIdVerifyMutationFn = (
    userid: string,
    passkeyCompletRegistrationRequestBody: PasskeyCompletRegistrationRequestBody,
 options?: SecondParameter<typeof customAxiosInstance<PasskeyAddedSuccessResponse>>,) => {
      return customAxiosInstance<PasskeyAddedSuccessResponse>(
      {url: `/passkey/add-passkey/verify/${userid}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passkeyCompletRegistrationRequestBody
    },
      options);
    }
  /**
 * This endpoint initiates the process to remove a passkey associated with a user's account.  
The user must be authenticated and authorized to remove a specific passkey, identified by the `credentialid`.  
Upon successful initiation, a passkey removal session is created, and options for the passkey removal request (such as challenge data) are returned.  
The challenge session is created to ensure that the request is authentic, and no unauthorized changes can be made to the passkey list.

**Important:** 
- The user must be authenticated using a valid access token (passed via cookies).
- The `userid` and `credentialid` parameters must match the currently authenticated user and the passkey being removed.

 * @summary Initiate Passkey removal for a user
 */
export const passkeyRemovePasskeyByIdInitMutationFn = (
    userid: string,
    credentialid: string,
 options?: SecondParameter<typeof customAxiosInstance<PasskeyGenerateRemoveKeySuccessResponse>>,) => {
      return customAxiosInstance<PasskeyGenerateRemoveKeySuccessResponse>(
      {url: `/passkey/remove-key/init/${userid}/${credentialid}`, method: 'POST'
    },
      options);
    }
  /**
 * This endpoint allows the authenticated user to remove a specific passkey credential from their account. The request must include the user ID and the credential ID of the passkey to be removed. The user can only remove their own passkeys. This action requires authentication and the provided session must be valid. If successful, the passkey will be permanently deleted from the system, and the session used for verification will be marked as consumed.

 * @summary Remove a passkey credential from a user's account
 */
export const passkeyRemovePasskeyByIdVerifyMutationFn = (
    userid: string,
    credentialid: string,
    passkeyCompletAuthenticationRequestBody: PasskeyCompletAuthenticationRequestBody,
 options?: SecondParameter<typeof customAxiosInstance<PasskeyRemovedSuccessResponse>>,) => {
      return customAxiosInstance<PasskeyRemovedSuccessResponse>(
      {url: `/passkey/remove-key/verify/${userid}/${credentialid}`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: passkeyCompletAuthenticationRequestBody
    },
      options);
    }
  /**
 * This endpoint allows you to retrieve all passkeys that are associated with a specific user by their unique `userid`.  The user must be authenticated and the `userid` in the path must match the authenticated user's ID to prevent unauthorized access. Each passkey returned will include essential details such as the credential ID, the associated provider (`aaguid`), the date it was created,  and the last time it was used. The response also includes metadata with the total count of passkeys retrieved.

 * @summary Retrieve all passkeys associated with a user.
 */
export const passkeyAllGetByUserIdQueryFn = (
    userid: string,
 options?: SecondParameter<typeof customAxiosInstance<PasskeyGetAllPasskeyByUserIdSuccessResponse>>,) => {
      return customAxiosInstance<PasskeyGetAllPasskeyByUserIdSuccessResponse>(
      {url: `/passkey/all/${userid}`, method: 'GET'
    },
      options);
    }
  export type PasskeySignUpInitMutationFnResult = NonNullable<Awaited<ReturnType<typeof passkeySignUpInitMutationFn>>>
export type PasskeySignUpVerifyMutationFnResult = NonNullable<Awaited<ReturnType<typeof passkeySignUpVerifyMutationFn>>>
export type PasskeySignInInitMutationFnResult = NonNullable<Awaited<ReturnType<typeof passkeySignInInitMutationFn>>>
export type PasskeySignInVerifyMutationFnResult = NonNullable<Awaited<ReturnType<typeof passkeySignInVerifyMutationFn>>>
export type PasskeyAddPasskeyByUserIdInitMutationFnResult = NonNullable<Awaited<ReturnType<typeof passkeyAddPasskeyByUserIdInitMutationFn>>>
export type PasskeyAddPasskeyByUserIdVerifyMutationFnResult = NonNullable<Awaited<ReturnType<typeof passkeyAddPasskeyByUserIdVerifyMutationFn>>>
export type PasskeyRemovePasskeyByIdInitMutationFnResult = NonNullable<Awaited<ReturnType<typeof passkeyRemovePasskeyByIdInitMutationFn>>>
export type PasskeyRemovePasskeyByIdVerifyMutationFnResult = NonNullable<Awaited<ReturnType<typeof passkeyRemovePasskeyByIdVerifyMutationFn>>>
export type PasskeyAllGetByUserIdQueryFnResult = NonNullable<Awaited<ReturnType<typeof passkeyAllGetByUserIdQueryFn>>>
