/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API for Password, Passkey, Magic Link, and OIDC Authentication
 * API for user registration and authentication using multiple methods: username/password with capability of 2fa, passkey (WebAuthn), magic link, and OIDC providers (Google, GitHub, etc.).

 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



/**
 * Registers a new user account by sending a **magic link** to the provided email address. 
The user can complete the signup process by clicking the link in the verification email. 
If the email is already associated with an existing account, the request will be rejected.  
This flow is typically used when passwordless authentication is enabled for the application.

 * @summary Register a new user using a magic link
 */
export const magicLinkSignUpMutationFnBodyNameMax = 64;

export const magicLinkSignUpMutationFnBodyEmailMax = 64;



export const magicLinkSignUpMutationFnBody = zod.object({
  "name": zod.string().min(1).max(magicLinkSignUpMutationFnBodyNameMax).describe('The user\'s full name'),
  "email": zod.email().min(1).max(magicLinkSignUpMutationFnBodyEmailMax)
})

export const magicLinkSignUpMutationFnResponse = zod.object({
  "success": zod.literal(true),
  "statusCode": zod.literal(201),
  "message": zod.string(),
  "data": zod.object({
  "user": zod.object({
  "_id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "isEmailVerified": zod.boolean(),
  "userPreferences": zod.object({
  "enable2FA": zod.boolean(),
  "emailNotification": zod.boolean()
}),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
}).optional(),
  "isMagicLinkEmailSend": zod.boolean().optional(),
  "nextStep": zod.enum(['CHECK_EMAIL_FOR_MAGIC_LINK']).optional()
}),
  "metadata": zod.object({
  "timestamp": zod.iso.datetime({}).describe('The exact server-side timestamp when the response was generated.'),
  "requestId": zod.string().describe('A unique identifier for the request, useful for tracing logs and debugging.'),
  "count": zod.number().optional().describe('The total number of items returned in the response (if applicable).')
}).describe('Contains metadata related to the request and response, such as timestamps, request tracking IDs, and result counts.\n')
})

/**
 * Initiates a passwordless sign-in flow by sending a magic link to the user email address. 
The user can authenticate by clicking the link received in their inbox. 
If the email is not associated with any account, the request will fail with a 404 response. 
This endpoint is typically used in passwordless authentication systems.

 * @summary Sign in a user using a magic link
 */
export const magicLinkSignInMutationFnBodyEmailMax = 64;



export const magicLinkSignInMutationFnBody = zod.object({
  "email": zod.email().min(1).max(magicLinkSignInMutationFnBodyEmailMax)
})

export const magicLinkSignInMutationFnResponse = zod.object({
  "success": zod.literal(true),
  "statusCode": zod.literal(200),
  "message": zod.string(),
  "data": zod.object({
  "isMagicLinkEmailSend": zod.boolean().optional(),
  "nextStep": zod.enum(['CHECK_EMAIL_FOR_MAGIC_LINK']).optional()
}),
  "metadata": zod.object({
  "timestamp": zod.iso.datetime({}).describe('The exact server-side timestamp when the response was generated.'),
  "requestId": zod.string().describe('A unique identifier for the request, useful for tracing logs and debugging.'),
  "count": zod.number().optional().describe('The total number of items returned in the response (if applicable).')
}).describe('Contains metadata related to the request and response, such as timestamps, request tracking IDs, and result counts.\n')
})

/**
 * Resends a new generated magic link to the user's email address. 
This endpoint can be used when the user did not receive or accidentally deleted 
the original magic link for verification or sign-in. 
If the email does not correspond to an existing user, the request will fail with a 404 response. 
This operation is commonly used in passwordless authentication systems to handle failed or lost verification emails.

 * @summary Resend a magic link for email verification or sign-in
 */
export const magicLinkResendMutationFnBodyEmailMax = 64;



export const magicLinkResendMutationFnBody = zod.object({
  "email": zod.email().min(1).max(magicLinkResendMutationFnBodyEmailMax)
})

export const magicLinkResendMutationFnResponse = zod.object({
  "success": zod.literal(true),
  "statusCode": zod.literal(200),
  "message": zod.string(),
  "data": zod.object({
  "isMagicLinkEmailSend": zod.boolean().optional(),
  "nextStep": zod.enum(['CHECK_EMAIL_FOR_MAGIC_LINK']).optional()
}),
  "metadata": zod.object({
  "timestamp": zod.iso.datetime({}).describe('The exact server-side timestamp when the response was generated.'),
  "requestId": zod.string().describe('A unique identifier for the request, useful for tracing logs and debugging.'),
  "count": zod.number().optional().describe('The total number of items returned in the response (if applicable).')
}).describe('Contains metadata related to the request and response, such as timestamps, request tracking IDs, and result counts.\n')
})

/**
 * Verifies a user's email or signs them in by validating the provided magic link token. 
This endpoint is typically triggered when the user clicks on the magic link sent to their email. 
Upon successful verification, authentication cookies or tokens are issued to establish the session.

 * @summary Verify a user's email using a magic link token
 */
export const magicLinkAuthenticateQueryFnParams = zod.object({
  "token": zod.string().describe('A unique, single-use token included in the magic link sent to the user\'s email.  It is used to verify the user\'s email ownership and complete the sign-in process.\n')
})

export const magicLinkAuthenticateQueryFnResponse = zod.object({
  "success": zod.literal(true),
  "statusCode": zod.literal(200),
  "message": zod.string(),
  "data": zod.object({
  "user": zod.object({
  "_id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "isEmailVerified": zod.boolean(),
  "userPreferences": zod.object({
  "enable2FA": zod.boolean(),
  "emailNotification": zod.boolean()
}),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
}),
  "nextStep": zod.enum(['OK']),
  "mfaRequired": zod.literal(false)
}),
  "metadata": zod.object({
  "timestamp": zod.iso.datetime({}).describe('The exact server-side timestamp when the response was generated.'),
  "requestId": zod.string().describe('A unique identifier for the request, useful for tracing logs and debugging.'),
  "count": zod.number().optional().describe('The total number of items returned in the response (if applicable).')
}).describe('Contains metadata related to the request and response, such as timestamps, request tracking IDs, and result counts.\n')
})

