/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API for Password, Passkey, Magic Link, and OIDC Authentication
 * API for user registration and authentication using multiple methods: username/password with capability of 2fa, passkey (WebAuthn), magic link, and OIDC providers (Google, GitHub, etc.).

 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



/**
 * Initiates the setup process for Multi-Factor Authentication (MFA) using TOTP (Time-Based One-Time Password). 
Returns a temporary secret key and a QR code that the user can scan in their authenticator app (e.g., Google Authenticator, Authy). 
The temporary secret must be verified by the user to finalize MFA enrollment. 
This endpoint requires the user to be authenticated via a valid access token cookie.

 * @summary Retrieve temporary TOTP secret and QR code for MFA setup
 */
export const mfaSetupQueryFnResponseDataSecretRegExp = new RegExp('^[A-Z2-7]+=*$');


export const mfaSetupQueryFnResponse = zod.object({
  "success": zod.literal(true),
  "statusCode": zod.literal(200),
  "message": zod.string(),
  "data": zod.object({
  "secret": zod.string().regex(mfaSetupQueryFnResponseDataSecretRegExp).describe('Base32-encoded TOTP secret for the user. This secret is used to generate OTP codes.'),
  "qrImageUrl": zod.string().describe('Base64-encoded PNG image of the QR code for TOTP setup. Can be rendered in clients as an image.')
}),
  "metadata": zod.object({
  "timestamp": zod.iso.datetime({}).describe('The exact server-side timestamp when the response was generated.'),
  "requestId": zod.string().describe('A unique identifier for the request, useful for tracing logs and debugging.'),
  "count": zod.number().optional().describe('The total number of items returned in the response (if applicable).')
}).describe('Contains metadata related to the request and response, such as timestamps, request tracking IDs, and result counts.\n')
})

/**
 * Verifies the multi-factor authentication (MFA) code provided by the user. This step is required after MFA setup or during a login flow to validate the one-time code generated by the authenticator app or sent via email/SMS. Upon successful verification, the MFA setup is confirmed or the login session is allowed.

 * @summary Verify the MFA code for a user
 */
export const mfaVerifyMutationFnBody = zod.object({
  "code": zod.string().describe('The 6-digit one-time password (OTP) generated by the user\'s authenticator app or received via the selected MFA method.\n')
})

export const mfaVerifyMutationFnResponse = zod.object({
  "success": zod.literal(true),
  "statusCode": zod.literal(200),
  "message": zod.string(),
  "data": zod.object({
  "userPreferences": zod.object({
  "enable2FA": zod.literal(true).optional(),
  "backupCodes": zod.array(zod.string())
})
}),
  "metadata": zod.object({
  "timestamp": zod.iso.datetime({}).describe('The exact server-side timestamp when the response was generated.'),
  "requestId": zod.string().describe('A unique identifier for the request, useful for tracing logs and debugging.'),
  "count": zod.number().optional().describe('The total number of items returned in the response (if applicable).')
}).describe('Contains metadata related to the request and response, such as timestamps, request tracking IDs, and result counts.\n')
})

/**
 * Revokes (disables) Two-Factor Authentication (2FA) for the authenticated user.   The user must provide a valid MFA verification code generated by their authenticator app.   Once verified, the user's 2FA secret and backup codes will be permanently removed.

 * @summary Disable (revoke) Two-Factor Authentication (2FA) for the current user
 */
export const mfaRevokeMutationFnBody = zod.object({
  "code": zod.string().describe('The 6-digit one-time password (OTP) generated by the user\'s authenticator app.   Must be valid at the time of request.\n')
})

export const mfaRevokeMutationFnResponse = zod.object({
  "success": zod.literal(true),
  "statusCode": zod.literal(200),
  "message": zod.string(),
  "data": zod.object({
  "user": zod.object({
  "_id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "isEmailVerified": zod.boolean(),
  "userPreferences": zod.object({
  "enable2FA": zod.boolean(),
  "emailNotification": zod.boolean()
}),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
}).optional()
}),
  "metadata": zod.object({
  "timestamp": zod.iso.datetime({}).describe('The exact server-side timestamp when the response was generated.'),
  "requestId": zod.string().describe('A unique identifier for the request, useful for tracing logs and debugging.'),
  "count": zod.number().optional().describe('The total number of items returned in the response (if applicable).')
}).describe('Contains metadata related to the request and response, such as timestamps, request tracking IDs, and result counts.\n')
})

/**
 * Disables Multi-Factor Authentication (2FA) for the currently authenticated user using one of their previously generated backup codes.   This endpoint can be used when the user no longer has access to their authenticator app but still possesses a valid backup code.   Upon successful verification of the provided backup code, all remaining backup codes are invalidated, the MFA secret is removed, and 2FA is fully disabled for the account.

 * @summary Disable Two-Factor Authentication (2FA) using a backup code
 */
export const mfaBackupCodeConsumeMutationFnBody = zod.object({
  "backupCode": zod.string().describe('The valid unused backup code associated with the user\'s account.')
})

export const mfaBackupCodeConsumeMutationFnResponse = zod.object({
  "success": zod.literal(true),
  "statusCode": zod.literal(200),
  "message": zod.string(),
  "data": zod.object({
  "user": zod.object({
  "_id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "isEmailVerified": zod.boolean(),
  "userPreferences": zod.object({
  "enable2FA": zod.boolean(),
  "emailNotification": zod.boolean()
}),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
}).optional()
}),
  "metadata": zod.object({
  "timestamp": zod.iso.datetime({}).describe('The exact server-side timestamp when the response was generated.'),
  "requestId": zod.string().describe('A unique identifier for the request, useful for tracing logs and debugging.'),
  "count": zod.number().optional().describe('The total number of items returned in the response (if applicable).')
}).describe('Contains metadata related to the request and response, such as timestamps, request tracking IDs, and result counts.\n')
})

/**
 * Authenticates a user by consuming one of their valid MFA backup codes. This endpoint is typically used when a user cannot access their authenticator app but has saved backup codes.   Upon successful verification, a new authenticated session is created, access and refresh tokens are issued, and the used backup code is invalidated (removed from the account).   The `mfaToken` cookie used during the MFA flow is cleared upon successful login.

 * @summary Log in using a backup code
 */
export const mfaBackupCodeLoginMutationFnBody = zod.object({
  "backupCode": zod.string().describe('The valid unused backup code associated with the user\'s account.')
})

export const mfaBackupCodeLoginMutationFnResponse = zod.object({
  "success": zod.literal(true),
  "statusCode": zod.literal(200),
  "message": zod.string(),
  "data": zod.object({
  "user": zod.object({
  "_id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "isEmailVerified": zod.boolean(),
  "userPreferences": zod.object({
  "enable2FA": zod.boolean(),
  "emailNotification": zod.boolean()
}),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
}),
  "nextStep": zod.enum(['OK']),
  "mfaRequired": zod.literal(false)
}),
  "metadata": zod.object({
  "timestamp": zod.iso.datetime({}).describe('The exact server-side timestamp when the response was generated.'),
  "requestId": zod.string().describe('A unique identifier for the request, useful for tracing logs and debugging.'),
  "count": zod.number().optional().describe('The total number of items returned in the response (if applicable).')
}).describe('Contains metadata related to the request and response, such as timestamps, request tracking IDs, and result counts.\n')
})

/**
 * Validates the one-time MFA code provided by the user during the login process.   This endpoint finalizes the multi-factor authentication (MFA) login flow by verifying the 6-digit time-based one-time password (TOTP) generated by the user’s authenticator app.   Upon successful verification, a new authenticated session is created, and both access and refresh tokens are issued. The temporary `mfaToken` cookie is cleared once login is complete.

 * @summary Verify MFA code during login
 */
export const mfaVerifyLoginMutationFnBody = zod.object({
  "code": zod.string().describe('The 6-digit one-time password (OTP) generated by the user\'s authenticator app.   Must be valid at the time of request.\n')
})

export const mfaVerifyLoginMutationFnResponse = zod.object({
  "success": zod.literal(true),
  "statusCode": zod.literal(200),
  "message": zod.string(),
  "data": zod.object({
  "user": zod.object({
  "_id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "isEmailVerified": zod.boolean(),
  "userPreferences": zod.object({
  "enable2FA": zod.boolean(),
  "emailNotification": zod.boolean()
}),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
}),
  "nextStep": zod.enum(['OK']),
  "mfaRequired": zod.literal(false)
}),
  "metadata": zod.object({
  "timestamp": zod.iso.datetime({}).describe('The exact server-side timestamp when the response was generated.'),
  "requestId": zod.string().describe('A unique identifier for the request, useful for tracing logs and debugging.'),
  "count": zod.number().optional().describe('The total number of items returned in the response (if applicable).')
}).describe('Contains metadata related to the request and response, such as timestamps, request tracking IDs, and result counts.\n')
})

/**
 * Verifies the one-time MFA code submitted by the user in order to proceed with a password reset.   Upon successful verification, a password reset email is sent to the user's registered email address with a link to complete the password change process.   This endpoint also clears the temporary MFA token cookie to prevent reuse.

 * @summary Verify MFA code for password reset
 */
export const mfaVerifyForgotPasswordMutationFnBody = zod.object({
  "code": zod.string().describe('The 6-digit one-time password (OTP) generated by the user\'s authenticator app.   Must be valid at the time of request.\n')
})

export const mfaVerifyForgotPasswordMutationFnResponse = zod.object({
  "success": zod.literal(true),
  "statusCode": zod.literal(200),
  "message": zod.string(),
  "data": zod.object({
  "nextStep": zod.enum(['OK'])
}),
  "metadata": zod.object({
  "timestamp": zod.iso.datetime({}).describe('The exact server-side timestamp when the response was generated.'),
  "requestId": zod.string().describe('A unique identifier for the request, useful for tracing logs and debugging.'),
  "count": zod.number().optional().describe('The total number of items returned in the response (if applicable).')
}).describe('Contains metadata related to the request and response, such as timestamps, request tracking IDs, and result counts.\n')
})

