/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API for Password, Passkey, Magic Link, and OIDC Authentication
 * API for user registration and authentication using multiple methods: username/password with capability of 2fa, passkey (WebAuthn), magic link, and OIDC providers (Google, GitHub, etc.).

 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



/**
 * Handles the callback from Google after user authorization. Expects `code` and `state` query parameters returned by Google. 
**Flow:** 1. Verify that the `state` exists, has not expired, and has not been consumed. 2. Exchange the authorization code for tokens (access token, refresh token, ID token). 3. Validate the ID token against Google's JWKS endpoint and verify claims. 4. Create or find a corresponding user in the local database. 5. Set authentication cookies (`accessToken` and `refreshToken`). 6. Return a JSON response indicating successful login.

 * @summary Authenticate user via Google OIDC callback
 */
export const oidcGoogleCallbackGetQueryFnQueryParams = zod.object({
  "code": zod.string().describe('Authorization code returned by Google'),
  "state": zod.string().describe('Unique state generated during the authorization request')
})

export const oidcGoogleCallbackGetQueryFnResponse = zod.object({
  "success": zod.literal(true),
  "statusCode": zod.literal(200),
  "message": zod.string(),
  "data": zod.object({
  "user": zod.object({
  "_id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "isEmailVerified": zod.boolean(),
  "userPreferences": zod.object({
  "enable2FA": zod.boolean(),
  "emailNotification": zod.boolean()
}),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
}),
  "nextStep": zod.enum(['OK']),
  "mfaRequired": zod.literal(false)
}),
  "metadata": zod.object({
  "timestamp": zod.iso.datetime({}).describe('The exact server-side timestamp when the response was generated.'),
  "requestId": zod.string().describe('A unique identifier for the request, useful for tracing logs and debugging.'),
  "count": zod.number().optional().describe('The total number of items returned in the response (if applicable).')
}).describe('Contains metadata related to the request and response, such as timestamps, request tracking IDs, and result counts.\n')
})

/**
 * Handles the callback from Github after user authorization. Expects `code` and `state` query parameters returned by Github. 
**Flow:** 1. Verify that the `state` exists, has not expired, and has not been consumed. 2. Exchange the authorization code for tokens (access token, refresh token, ID token). 3. Validate the ID token against Github's JWKS endpoint and verify claims. 4. Create or find a corresponding user in the local database. 5. Set authentication cookies (`accessToken` and `refreshToken`). 6. Return a JSON response indicating successful login.

 * @summary Authenticate user via Github OIDC callback
 */
export const oidcGithubCallbackGetQueryFnQueryParams = zod.object({
  "code": zod.string().describe('Authorization code returned by Github'),
  "state": zod.string().describe('Unique state generated during the authorization request')
})

export const oidcGithubCallbackGetQueryFnResponse = zod.object({
  "success": zod.literal(true),
  "statusCode": zod.literal(200),
  "message": zod.string(),
  "data": zod.object({
  "user": zod.object({
  "_id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "isEmailVerified": zod.boolean(),
  "userPreferences": zod.object({
  "enable2FA": zod.boolean(),
  "emailNotification": zod.boolean()
}),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
}),
  "nextStep": zod.enum(['OK']),
  "mfaRequired": zod.literal(false)
}),
  "metadata": zod.object({
  "timestamp": zod.iso.datetime({}).describe('The exact server-side timestamp when the response was generated.'),
  "requestId": zod.string().describe('A unique identifier for the request, useful for tracing logs and debugging.'),
  "count": zod.number().optional().describe('The total number of items returned in the response (if applicable).')
}).describe('Contains metadata related to the request and response, such as timestamps, request tracking IDs, and result counts.\n')
})

