/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * API for Password, Passkey, Magic Link, and OIDC Authentication
 * API for user registration and authentication using multiple methods: username/password with capability of 2fa, passkey (WebAuthn), magic link, and OIDC providers (Google, GitHub, etc.).

 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



/**
 * Retrieves a list of all **active login sessions** associated with the authenticated user.   This endpoint allows a user to view all currently valid sessions across devices and browsers, helping with account activity monitoring and session management.  
Each returned session includes device information (`userAgent`), creation and expiration timestamps, and a boolean flag (`isCurrent`) indicating whether it corresponds to the current active session (the one used to make the request).  
Expired sessions are automatically filtered out and are **not included** in the response.

 * @summary Retrieve all active sessions for the authenticated user
 */
export const sessionAllGetQueryFnResponse = zod.object({
  "success": zod.boolean().optional().describe('Indicates whether the operation was successful'),
  "statusCode": zod.number().optional().describe('HTTP status code of the response'),
  "message": zod.string().optional(),
  "data": zod.object({
  "sessions": zod.array(zod.object({
  "_id": zod.string().optional().describe('Unique identifier of the session.'),
  "userId": zod.string().optional().describe('Unique identifier of the user who owns the session.'),
  "userAgent": zod.object({
  "browser": zod.string().optional(),
  "version": zod.string().optional(),
  "os": zod.string().optional(),
  "platform": zod.string().optional()
}).optional(),
  "expiredAt": zod.iso.datetime({}).optional().describe('The expiration date and time of the session.'),
  "createdAt": zod.iso.datetime({}).optional().describe('The creation date and time of the session.'),
  "isCurrent": zod.boolean().optional().describe('Indicates if this is the current session.')
})).optional()
}).optional(),
  "metadata": zod.object({
  "timestamp": zod.iso.datetime({}).describe('The exact server-side timestamp when the response was generated.'),
  "requestId": zod.string().describe('A unique identifier for the request, useful for tracing logs and debugging.'),
  "count": zod.number().optional().describe('The total number of items returned in the response (if applicable).')
}).optional().describe('Contains metadata related to the request and response, such as timestamps, request tracking IDs, and result counts.\n')
})

/**
 * Retrieves the **current active session** for the authenticated user, based on the session ID stored in the request context.   This endpoint is primarily used to identify the session associated with the current request and to retrieve minimal user information .

 * @summary Retrieve the current user session
 */
export const sessionGetCurrentQueryFnResponse = zod.object({
  "success": zod.boolean().describe('Indicates whether the operation was successful'),
  "statusCode": zod.number().describe('HTTP status code of the response'),
  "message": zod.string(),
  "data": zod.object({
  "user": zod.object({
  "_id": zod.string(),
  "name": zod.string(),
  "email": zod.string(),
  "isEmailVerified": zod.boolean(),
  "userPreferences": zod.object({
  "enable2FA": zod.boolean(),
  "emailNotification": zod.boolean()
}),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
}).optional()
}),
  "metadata": zod.object({
  "timestamp": zod.iso.datetime({}).describe('The exact server-side timestamp when the response was generated.'),
  "requestId": zod.string().describe('A unique identifier for the request, useful for tracing logs and debugging.'),
  "count": zod.number().optional().describe('The total number of items returned in the response (if applicable).')
}).describe('Contains metadata related to the request and response, such as timestamps, request tracking IDs, and result counts.\n')
})

/**
 * Deletes a specific user session identified by its ID.  The operation validates that the session exists and that the authenticated user has permission to delete it.  If the deleted session is the current session of the user, authentication cookies will be cleared, effectively logging the user out.
Responses include a success message and, if the current session was deleted, a `nextStep` indicating that the user should be redirected to the login page.
Possible errors:
  - 403 Forbidden: If the user tries to delete a session that does not belong to them.
  - 404 Not Found: If the session ID does not exist.

 * @summary Delete a user session by ID
 */
export const sessionRemoveByIdMutationFnParams = zod.object({
  "id": zod.string().describe('The unique identifier of the session who will be deleted.')
})

export const sessionRemoveByIdMutationFnResponse = zod.object({
  "success": zod.boolean().describe('Indicates whether the operation was successful'),
  "statusCode": zod.number().describe('HTTP status code of the response'),
  "message": zod.string().describe('A human-readable message describing the result'),
  "data": zod.object({
  "nextStep": zod.string().optional().describe('If the deleted session was the current session, indicates the next action for the client (e.g., LOGIN.LOGOUT).\n')
}),
  "metadata": zod.object({
  "timestamp": zod.iso.datetime({}).describe('The exact server-side timestamp when the response was generated.'),
  "requestId": zod.string().describe('A unique identifier for the request, useful for tracing logs and debugging.'),
  "count": zod.number().optional().describe('The total number of items returned in the response (if applicable).')
}).describe('Contains metadata related to the request and response, such as timestamps, request tracking IDs, and result counts.\n')
})

