const enum ErrorCode {
  AUTH_EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN",
  AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND",
  AUTH_NOT_FOUND = "AUTH_NOT_FOUND",
  AUTH_TOO_MANY_ATTEMPTS = "AUTH_TOO_MANY_ATTEMPTS",
  AUTH_UNAUTHORIZED_ACCESS = "AUTH_UNAUTHORIZED_ACCESS",
  AUTH_TOKEN_NOT_FOUND = "AUTH_TOKEN_NOT_FOUND",
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  AUTH_SESSION_INVALID = "AUTH_SESSION_INVALID",
  AUTH_SESSION_MISMATCH = "AUTH_SESSION_MISMATCH",
  AUTH_SESSION_NOT_FOUND = "AUTH_SESSION_NOT_FOUND",
  AUTH_SIGNATURE_INVALID = "AUTH_SIGNATURE_INVALID",
  MFA_ALREADY_ENABLED = "MFA_ALREADY_ENABLED",
  MFA_ALREADY_DISABLED = "MFA_ALREADY_DISABLED",
  MFA_EXPIRED_TEMP_SECRET = "MFA_EXPIRED_TEMP_SECRET",
  MFA_INVALID_VERIFICATION_CODE = "MFA_INVALID_VERIFICATION_CODE",
  BACKUPCODE_INVALID_CODE = "BACKUPCODE_INVALID",
  // General Access Errors
  ACCESS_UNAUTHORIZED = "ACCESS_UNAUTHORIZED",
  ACCESS_FORBIDDEN = "ACCESS_FORBIDDEN",
  // Validation and Resource Errors
  VALIDATION_ERROR = "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  INVALID_FORMAT = "INVALID_FORMAT",
  // System Errors
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  VERIFICATION_ERROR = "VERIFICATION_ERROR",
  AUTH_PROVIDER_ERROR = "AUTH_PROVIDER_ERROR",
}

export { ErrorCode };
