const enum ErrorCode {
  // Email & Password Auth
  AUTH_EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND",
  AUTH_PASSWORD_REUSE_NOT_ALLOWED = "AUTH_PASSWORD_REUSE_NOT_ALLOWED",
  // General Authentication Token Error
  AUTH_TOKEN_NOT_FOUND = "AUTH_ACCESS_TOKEN_NOT_FOUND",
  AUTH_TOKEN_INVALID = "AUTH_ACCESS_TOKEN_INVALID",
  AUTH_TOKEN_EXPIRED = "AUTH_ACCESS_TOKEN_EXPIRED",
  AUTH_TOKEN_USER_NOT_FOUND = "AUTH_ACCESS_TOKEN_USER_NOT_FOUND",
  AUTH_TOKEN_SESSION_INVALID = "AUTH_ACCESS_TOKEN_SESSION_INVALID",
  AUTH_TOKEN_SESSION_MISMATCH = "AUTH_ACCESS_TOKEN_SESSION_MISMATCH",

  // Verification Codes Erros
  VERIFICATION_CODE_ERROR_CODE_NOT_FOUND = "VERIFICATION_CODE_ERROR_CODE_NOT_FOUND",
  VERIFICATION_CODE_ERROR_CODE_CONSUMED = "VERIFICATION_CODE_ERROR_CODE_CONSUMED",
  VERIFICATION_CODE_ERROR_CODE_EXPIRED = "VERIFICATION_CODE_ERROR_CODE_EXPIRED",

  // Email Service
  EMAIL_SERVICE_ERROR = "EMAIL_SERVICE_ERROR",

  // MFA
  MFA_ALREADY_ENABLED = "MFA_ALREADY_ENABLED",
  MFA_ALREADY_DISABLED = "MFA_ALREADY_DISABLED",
  MFA_EXPIRED_TEMP_SECRET = "MFA_EXPIRED_TEMP_SECRET",
  MFA_INVALID_VERIFICATION_CODE = "MFA_INVALID_VERIFICATION_CODE",
  MFA_INVALID_SESSION = "MFA_INVALID_SESSION",
  // MFA Token Erros
  AUTH_MFA_TOKEN_TYPE_INVALID = "AUTH_MFA_TOKEN_TYPE_INVALID",
  AUTH_MFA_INVALID_ENDPOINT = " AUTH_MFA_INVALID_ENDPOINT",
  AUTH_MFA_TOKEN_PURPOSE_MISMATCH = "AUTH_MFA_TOKEN_PURPOSE_MISMATCH",
  // Magic Link Token Errors
  AUTH_MAGIC_LINK_TOKEN_TYPE_INVALID = "AUTH_MAGIC_LINK_TOKEN_TYPE_INVALID",

  AUTH_TOO_MANY_ATTEMPTS = "AUTH_TOO_MANY_ATTEMPTS",
  AUTH_UNAUTHORIZED_ACCESS = "AUTH_UNAUTHORIZED_ACCESS",
  AUTH_SESSION_NOT_FOUND = "AUTH_SESSION_NOT_FOUND",
  AUTH_SIGNATURE_INVALID = "AUTH_SIGNATURE_INVALID",
  AUTH_INVALID_PATH = "AUTH_INVALID_PATH",
  AUTH_INVALID_TOKEN_PURPOSE = "AUTH_INVALID_TOKEN_PURPOSE",
  OIDC_MISSING_SESSION = "OIDC_MISSING_SESSION",
  OIDC_EXPIRED_SESSION = "OIDC_EXPIRED_SESSION",
  OIDC_FAILED_AUTHENTIFICATION = "OIDC_FAILED_AUTHENTIFICATION",
  MAGIC_LINK_INVALID_OR_CONSUMED = "MAGIC_LINK_INVALID_OR_CONSUMED",
  MAGIC_LINK_INVALID_TOKEN_TYPE = "MAGIC_LINK_INVALID_TOKEN_TYPE",
  BACKUPCODE_INVALID_CODE = "BACKUPCODE_INVALID",
  PASSKEY_CHALLENGE_INVALID = "PASSKEY_CHALLENGE_INVALID",
  PASSKEY_CHALLENGE_ALREADY_CONSUMED = "PASSKEY_CHALLENGE_ALREADY_CONSUMED",
  PASSKEY_CHALLENGE__INVALID_PURPOSE = "PASSKEY_CHALLENGE__INVALID_PURPOSE",
  // General Access Errors
  ACCESS_UNAUTHORIZED = "ACCESS_UNAUTHORIZED",
  ACCESS_FORBIDDEN = "ACCESS_FORBIDDEN",
  // Validation and Resource Errors
  VALIDATION_ERROR_INVALID_REQUEST_BODY = "VALIDATION_ERROR_INVALID_REQUEST_BODY",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  INVALID_JSON_FORMAT = "INVALID_JSON_FORMAT",
  // System Errors
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  AUTH_PROVIDER_ERROR = "AUTH_PROVIDER_ERROR",
  // Too Many Requests
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
}

export { ErrorCode };
