const enum LOGIN {
  CONFIRM_SIGN_UP = "CONFIRM_SIGN_UP",
  OK = "OK",
  MFA_REQUIRED = "MFA_REQUIRED",
  CONFIRMED_EMAIL_RETURN_TO_LOGIN = "CONFIRMED_EMAIL_RETURN_TO_LOGIN",
  CHECK_EMAIL_FOR_MAGIC_LINK = "CHECK_EMAIL_FOR_MAGIC_LINK",
  LOGOUT = "LOGOUT",
}
export default LOGIN;
