const enum ErrorCode {
  // Email & Password Auth
  AUTH_EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_EMAIL_NOT_FOUND = "AUTH_EMAIL_NOT_FOUND",
  AUTH_EMAIL_ALREADY_VERIFIED = "AUTH_EMAIL_ALREADY_VERIFIED",
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND",
  AUTH_PASSWORD_REUSE_NOT_ALLOWED = "AUTH_PASSWORD_REUSE_NOT_ALLOWED",
  AUTH_SESSION_NOT_FOUND = "AUTH_SESSION_NOT_FOUND",
  // Email & Password Auth Token Errors
  AUTH_ACCESS_TOKEN_TYPE_INVALID = "AUTH_ACCESS_TOKEN_TYPE_INVALID",
  AUTH_REFRESH_TOKEN_TYPE_INVALID = "AUTH_REFRESH_TOKEN_TYPE_INVALID",
  AUTH_REFRESH_TOKEN_SESSION_INVALID = "AUTH_REFRESH_TOKEN_SESSION_INVALID",
  AUTH_REFRESH_TOKEN_SESSION_EXPIRED = "AUTH_REFRESH_TOKEN_SESSION_EXPIRED",
  // General Authentication Token Error
  AUTH_TOKEN_NOT_FOUND = "AUTH_ACCESS_TOKEN_NOT_FOUND",
  AUTH_TOKEN_INVALID = "AUTH_ACCESS_TOKEN_INVALID",
  AUTH_TOKEN_EXPIRED = "AUTH_ACCESS_TOKEN_EXPIRED",
  AUTH_TOKEN_USER_NOT_FOUND = "AUTH_ACCESS_TOKEN_USER_NOT_FOUND",
  AUTH_TOKEN_SESSION_INVALID = "AUTH_ACCESS_TOKEN_SESSION_INVALID",
  AUTH_TOKEN_SESSION_MISMATCH = "AUTH_ACCESS_TOKEN_SESSION_MISMATCH",
  AUTH_TOKEN_INVALID_TYPE = "AUTH_TOKEN_INVALID_TYPE",
  // Verification Codes Erros
  VERIFICATION_CODE_ERROR_CODE_NOT_FOUND = "VERIFICATION_CODE_ERROR_CODE_NOT_FOUND",
  VERIFICATION_CODE_ERROR_CODE_CONSUMED = "VERIFICATION_CODE_ERROR_CODE_CONSUMED",
  VERIFICATION_CODE_ERROR_CODE_EXPIRED = "VERIFICATION_CODE_ERROR_CODE_EXPIRED",
  // Email Service
  EMAIL_SERVICE_ERROR = "EMAIL_SERVICE_ERROR",
  // MFA
  MFA_ALREADY_ENABLED = "MFA_ALREADY_ENABLED",
  MFA_ALREADY_DISABLED = "MFA_ALREADY_DISABLED",
  MFA_EXPIRED_TEMP_SECRET = "MFA_EXPIRED_TEMP_SECRET",
  MFA_INVALID_VERIFICATION_CODE = "MFA_INVALID_VERIFICATION_CODE",
  MFA_NOT_ENABLED = "MFA_NOT_ENABLED",
  // MFA Token Erros
  AUTH_MFA_TOKEN_TYPE_INVALID = "AUTH_MFA_TOKEN_TYPE_INVALID",
  AUTH_MFA_INVALID_ENDPOINT = " AUTH_MFA_INVALID_ENDPOINT",
  AUTH_MFA_TOKEN_PURPOSE_MISMATCH = "AUTH_MFA_TOKEN_PURPOSE_MISMATCH",
  // Magic Link Token Errors
  AUTH_MAGIC_LINK_TOKEN_TYPE_INVALID = "AUTH_MAGIC_LINK_TOKEN_TYPE_INVALID",
  // BackupCodes
  BACKUPCODE_INVALID_CODE = "BACKUPCODE_INVALID",
  // OIDC Error Codes
  OIDC_SESSION_NOT_FOUND = "OIDC_SESSION_NOT_FOUND",
  OIDC_SESSION_CONSUMED = "OIDC_SESSION_CONSUMED",
  OIDC_SESSION_EXPIRED = "OIDC_SESSION_EXPIRED",
  OIDC_FAILED_AUTHENTIFICATION = "OIDC_FAILED_AUTHENTIFICATION",

  // PASSKEY Error Codes
  PASSKEY_CHALLENGE_SESSION_INVALID = "PASSKEY_CHALLENGE_SESSION_INVALID",
  PASSKEY_CHALLENGE_SESSION_CONSUMED = "PASSKEY_CHALLENGE_SESSION_CONSUMED",
  PASSKEY_CHALLENGE_SESSION__EXPIRED = "PASSKEY_CHALLENGE_SESSION__EXPIRED",
  PASSKEY_CHALLENGE_SESSION__INVALID_PURPOSE = "PASSKEY_CHALLENGE_SESSION__INVALID_PURPOSE",
  PASSKEY_CHALENGE_VERIFICATION_ERROR = "PASSKEY_CHALENGE_VERIFICATION_ERROR",
  PASSKEY_NOT_FOUND = "PASSKEY_NOT_FOUND",

  // General Access Errors
  ACCESS_UNAUTHORIZED = "ACCESS_UNAUTHORIZED",
  ACCESS_FORBIDDEN = "ACCESS_FORBIDDEN",

  // Validation and Resource Errors
  VALIDATION_ERROR_INVALID_REQUEST_BODY = "VALIDATION_ERROR_INVALID_REQUEST_BODY",
  INVALID_JSON_FORMAT = "INVALID_JSON_FORMAT",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",

  // System Errors
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",

  // Too Many Requests
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
}

export { ErrorCode };
